# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLO11 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 1 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.50, 0.25, 1024] # summary: 319 layers, 2624080 parameters, 2624064 gradients, 6.6 GFLOPs
  s: [0.50, 0.50, 1024] # summary: 319 layers, 9458752 parameters, 9458736 gradients, 21.7 GFLOPs
  m: [0.50, 1.00, 512] # summary: 409 layers, 20114688 parameters, 20114672 gradients, 68.5 GFLOPs
  l: [1.00, 1.00, 512] # summary: 631 layers, 25372160 parameters, 25372144 gradients, 87.6 GFLOPs
  x: [1.00, 1.50, 512] # summary: 631 layers, 56966176 parameters, 56966160 gradients, 196.0 GFLOPs

scale: 'm'


ch: 5
# YOLO11n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Split, []] #0

  # extra branch
  - [0, 1, ConvExtra, [64, 3, 2]] #1
  - [-1, 1, Conv, [128, 3, 2]] #2
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [-1, 1, Down, [256]] # 4
  - [-1, 2, C3k2, [512, False, 0.25]]

  - [0, 1, ConvImage, [64, 3, 2]] #6
  - [-1, 1, Conv, [128, 3, 2]] # 7
  - [-1, 2, C3k2, [256, False, 0.25]]
  - [[-1, 3], 1, AFI, [256, 2, 0]]
  - [-1, 1, Down, [256]] # 10
  - [-1, 2, C3k2, [512, False, 0.25]]
  - [[-1, 5], 1, AFI, [512, 2]]
  - [-1, 1, Down, [512]] # 13
  - [-1, 2, C3k2, [512, True]]
  - [-1, 1, Down, [1024]] # 15
  - [-1, 2, C3k2, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 17
  - [-1, 2, C2PSA_biformer, [1024]] # 18

# YOLO11n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] #19
  - [[14, -1], 1, Concat, [1]] 
  - [-1, 2, C3k2, [512, False]] 

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 22
  - [[12, -1], 1, Concat, [1]] 
  - [-1, 2, C3k2, [256, False]] 

  - [-1, 1, Conv, [256, 3, 2]] # 25
  - [[-1, 21], 1, Concat, [1]] 
  - [-1, 2, C3k2, [512, False]] 

  - [-1, 1, Conv, [512, 3, 2]] # 28
  - [[-1, 18], 1, Concat, [1]] 
  - [-1, 2, C3k2, [1024, True]] 

  - [[24, 27, 30], 1, Detect, [nc]] # 31
